const data = [
  {
    id: 2866,
    assigned_recruiter_name: null,
    branch_name: "OIS Manjri",
    verified_by: "Abhishek Mohapatra",
    location_name: "Pune",
    position_apply_id: null,
    designation_fk_name: "Secondary Teacher - French",
    academic_year: "2024-2025",
    employee_name: "Manoj Shidling",
    mrf_type: "replacement",
    position: "Secondary Teacher - French",
    position_type: null,
    department: null,
    zone: null,
    gender_preference: "any",
    experience: "1-3",
    priority: 1,
    minimum_qualification: "graduate_non_technical",
    no_of_vacancies: 1,
    max_budget: "492000",
    salary: "3-5",
    description: "",
    description_file: null,
    skill: "Teaching",
    job_type: "Full Time",
    is_active: true,
    status: "approve",
    remark: "Converting Part time teacher to full time.",
    mrf_replacement_emp_name: null,
    mrf_replacement_emp_id: null,
    replacement_json:
      '[{"index":0,"name":"Manrata Mishra","erp":"20235850092","file":"media/uploads/2024-06-03 17:38:37.947631EDUVATE Mail - Fwd_ Withdrawal from discontinuation of service_.pdf","exit_date":"2024-06-06","joining_date":"2024-06-07"}]',
    updated_at: "2024-06-03T18:15:37.029688",
    created_at: "2024-06-03T17:41:17.757287",
    file: null,
    mrf_status_date: "2024-06-03T18:15:37.238238",
    employee: 117543,
    assigned_recruter: null,
    position_type_fk: 262,
    department_fk: 1171,
    branch: 73,
    location: 1,
    academic_year_fk: 1,
    additional_recruiter: [],
  },
  {
    id: 2864,
    assigned_recruiter_name: "Darshan M",
    branch_name: "K12 Mumbai",
    verified_by: "Abhishek Mohapatra",
    location_name: "Mumbai",
    position_apply_id: 7300,
    designation_fk_name: "Data Analyst ",
    academic_year: "2024-2025",
    employee_name: "Shreeya Shah",
    mrf_type: "new_hire",
    position: "Data Analyst",
    position_type: null,
    department: null,
    zone: null,
    gender_preference: "any",
    experience: "1-3",
    priority: 2,
    minimum_qualification: "graduate_technical",
    no_of_vacancies: 1,
    max_budget: "1000000",
    salary: "7-10",
    description:
      "<p>Job Title MIS Executive / Sr. MIS executive Job Summary Provide an overview of your expectations from the candidate and include the daily tasks associated with the role. Also, include any additional perks and benefits to catch the candidates&rsquo; attention. You can also include primary skills and educational qualifications in this section. For example; we are looking for an MIS executive who will be responsible for timely designing and developing of a computer system along with developing strategies, specifications and keeping updated with the latest technological developments in the IT system. You must know how to analyse the operations and providing continuous suggestions for the improvement. You should strive for the advancement of knowledge through continuing education and research. Roles and Responsibilities 1. Planning, monitoring, analysing and troubleshooting IT frameworks. 2. Interpreting briefs and creating IT frameworks that meet all particulars and cost prerequisites. 3. Assisting with training and on boarding measures. 4. Composing job description for new positions, and helping with meeting and enlistment measures. 5. Guaranteeing staff consent to the organization, just as wellbeing and security guidelines consistently. 6. Looking after, overseeing, and refreshing software systems. 7. Overseeing advanced security and ensuring all anti-virus and firewalls are routinely refreshed. 8. Managing the expansion and maintenance of websites and guaranteeing the safety of clients&rsquo; information. 9. Analysing existing tasks, conventions, and processes, and making arrangements for development. 10. Conducting research, going to workshops, and networking with different experts in the business. Requirements 1. Bachelor degree in IT, computer science or related field 2. Master&rsquo;s degree will be an added advantage 3. Experience managing team 4. Certification course in MIS or related field 5. Ability to train junior resources 6. Knowledge of various MIS reporting tools Skills  Experience with a broad range of applications and software  Experience managing fleets of devices which includes mobile devices  Assessing and deciding software and hardware for various applications  Communication skills to clearly supervise and give clear instructions to colleagues  Organization goals to allocate resources effectively</p>",
    description_file: null,
    skill: "power bi, Excel, Sql",
    job_type: "Full Time",
    is_active: true,
    status: "approve",
    remark: "good candidate required",
    mrf_replacement_emp_name: null,
    mrf_replacement_emp_id: null,
    replacement_json: null,
    updated_at: "2024-06-03T17:26:31.329688",
    created_at: "2024-06-03T16:30:50.406969",
    file: "https://storage.googleapis.com/cvboxmedia/media/mrf/files/WhatsApp_Image_2024-06-03_at_16.29.52_3f5be3cc.jpg?Expires=1717525444&GoogleAccessId=sa-app-bucket%40prj-prod-service-k12.iam.gserviceaccount.com&Signature=oGOrxbzckBDyJs%2BM54zgfLFuvpcqXduM45Ky7JozrqJH6uV5WO0aZssJF0uHZ9VQW7h%2BAvq7KoSVP3nHvw6Oft0u48L3PxWqXt%2BDhFIbXS7vanBaK8ioqtiYBUMRTBOWm7eIC5Fh7UD%2FaSWZFqH30WhzkpIby68x3UHhF6B%2BIRSyv5wJIQRCBfNv%2Fhg9QaNsWh6hVGUPdKnsmXeNlm%2BejSyPM0Qo5EHzleiC%2BpS72jcjyOgHuD0nwyz1U5Bn865edN97EE0AOT%2FH1qz0n%2FH9X88ZsfRgw3hUiuI7wRz%2BcmzMGMJH2EGhESnb2QOGRurgz8tci8WQkMGAoYBBv9BQVA%3D%3D",
    mrf_status_date: "2024-06-03T17:05:18.336336",
    employee: 98447,
    assigned_recruter: 130136,
    position_type_fk: 234,
    department_fk: 1456,
    branch: 162,
    location: 3,
    academic_year_fk: 1,
    additional_recruiter: [],
  },
  {
    id: 2870,
    assigned_recruiter_name: null,
    branch_name: "OIS Chinchwad",
    verified_by: null,
    location_name: "Pune",
    position_apply_id: null,
    designation_fk_name: "Senior Faculty- OCFP",
    academic_year: "2024-2025",
    employee_name: "Madhavi",
    mrf_type: "replacement",
    position: "OCFP",
    position_type: null,
    department: null,
    zone: null,
    gender_preference: "any",
    experience: "1-3",
    priority: 1,
    minimum_qualification: "",
    no_of_vacancies: 1,
    max_budget: null,
    salary: "",
    description: "",
    description_file: null,
    skill: "",
    job_type: "Full Time",
    is_active: true,
    status: "pending",
    remark:
      "This faculty will be handling both Science and Math of Grade 6 & 7.",
    mrf_replacement_emp_name: null,
    mrf_replacement_emp_id: null,
    replacement_json:
      '[{"index":0,"name":"Mahak Arora ","erp":"20235870075","file":"media/uploads/2024-06-03 21:20:04.166537Replacement .png","exit_date":"2024-05-29","joining_date":"2024-06-05"}]',
    updated_at: "2024-06-03T21:23:37.887410",
    created_at: "2024-06-03T21:23:37.887426",
    file: null,
    mrf_status_date: null,
    employee: 104749,
    assigned_recruter: null,
    position_type_fk: 262,
    department_fk: 1189,
    branch: 71,
    location: 1,
    academic_year_fk: 1,
    additional_recruiter: [],
  },
  {
    id: 2869,
    assigned_recruiter_name: null,
    branch_name: "OIS JP Nagar",
    verified_by: null,
    location_name: "Bangalore",
    position_apply_id: null,
    designation_fk_name: "Teacher - Theatre",
    academic_year: "2024-2025",
    employee_name: "Triveni G",
    mrf_type: "replacement",
    position: "Teaching",
    position_type: null,
    department: null,
    zone: null,
    gender_preference: "any",
    experience: "1-3",
    priority: 1,
    minimum_qualification: "post_graduate_technical",
    no_of_vacancies: 1,
    max_budget: null,
    salary: "",
    description:
      "<p>Veena, - Appointed teacher, is absconding. She is not answering calls</p>",
    description_file: null,
    skill: "",
    job_type: "Full Time",
    is_active: true,
    status: "pending",
    remark: "Veena, - Appointed teacher, is absconding",
    mrf_replacement_emp_name: null,
    mrf_replacement_emp_id: null,
    replacement_json:
      '[{"index":0,"name":"Payaswini B S","erp":"20235100155","file":"media/uploads/2024-06-03 21:07:04.168621EDUVATE Mail - Request for resignation approval.pdf","exit_date":"2024-04-25","joining_date":"2024-06-03"}]',
    updated_at: "2024-06-03T21:09:16.593994",
    created_at: "2024-06-03T21:09:16.594006",
    file: null,
    mrf_status_date: null,
    employee: 133604,
    assigned_recruter: null,
    position_type_fk: 262,
    department_fk: 1241,
    branch: 17,
    location: 2,
    academic_year_fk: 1,
    additional_recruiter: [],
  },
  {
    id: 2435,
    assigned_recruiter_name: null,
    branch_name: "OIS Hennur",
    verified_by: null,
    location_name: "Bangalore",
    position_apply_id: null,
    designation_fk_name: "Senior Faculty - OCFP",
    academic_year: "2024-2025",
    employee_name: "Priya K",
    mrf_type: "new_hire",
    position: "Primary teacher",
    position_type: null,
    department: null,
    zone: null,
    gender_preference: "any",
    experience: "1-3",
    priority: 1,
    minimum_qualification: "graduate_non_technical",
    no_of_vacancies: 1,
    max_budget: null,
    salary: "1-3",
    description: "",
    description_file: null,
    skill: "excellent comand,communication skills,patience",
    job_type: "Full Time",
    is_active: false,
    status: "reject",
    remark: "Wrongly raised.",
    mrf_replacement_emp_name: null,
    mrf_replacement_emp_id: null,
    replacement_json: null,
    updated_at: "2024-05-16T10:20:57.205727",
    created_at: "2024-05-15T15:15:25.001038",
    file: "https://storage.googleapis.com/cvboxmedia/media/mrf/files/mrf_tea.png?Expires=1717525598&GoogleAccessId=sa-app-bucket%40prj-prod-service-k12.iam.gserviceaccount.com&Signature=hR3VzlGGcwDT5TaqjeWRxBw2t0dfUPLEpZ53i22plpscv5uxB0tv4W9CLo74tUX3BA%2B%2B8pB5bfD5lovtVvKREw8pM8C15KosdOgGGwMmodumgtKFAJqlfmTa5IWgp1uxY7JiGR3rlK9P%2F3eSTliwQ27xgg899UZec9hkokdVCUpF3vSKA2jzlOS2sHOg93qQsySj14EiY1tmgtXe08cD9ZaXn8edyWhvtLX4tDWctl7UkT4OU5oO6D6hYeuB4HzC7gFUJBYNvvwWI1JrIO8nUI%2FB4Ql%2B8%2BOrOckxbtmqQ1ewbiUSWXBNnbprsYlvlMx2c7H7riiMfANsNyYDGpv%2FVg%3D%3D",
    mrf_status_date: null,
    employee: 132109,
    assigned_recruter: null,
    position_type_fk: 244,
    department_fk: 892,
    branch: 107,
    location: 2,
    academic_year_fk: 1,
    additional_recruiter: [],
  },
  {
    id: 2296,
    assigned_recruiter_name: null,
    branch_name: "OIS Shastri Nagar",
    verified_by: null,
    location_name: "Jodhpur",
    position_apply_id: null,
    designation_fk_name: "Academic Head",
    academic_year: "2024-2025",
    employee_name: "Shalu Chouhan",
    mrf_type: "new_hire",
    position: "Middle Maths",
    position_type: null,
    department: null,
    zone: null,
    gender_preference: "any",
    experience: "",
    priority: 1,
    minimum_qualification: "",
    no_of_vacancies: 1,
    max_budget: null,
    salary: "",
    description: "",
    description_file: null,
    skill: "",
    job_type: "Full Time",
    is_active: true,
    status: "reject",
    remark: "To be re-raised with correct designation",
    mrf_replacement_emp_name: null,
    mrf_replacement_emp_id: null,
    replacement_json: null,
    updated_at: "2024-05-09T18:57:51.376125",
    created_at: "2024-05-08T09:25:51.801825",
    file: "https://storage.googleapis.com/cvboxmedia/media/mrf/files/Screenshot_2024-05-07_141427.png?Expires=1717525599&GoogleAccessId=sa-app-bucket%40prj-prod-service-k12.iam.gserviceaccount.com&Signature=QatzX4Wh4efFQgfryzPaIPl0G8fQTms1oM2nrpRIUbA08%2FJQsUg5j5c1I80ul3LiOBEiOFSuUVa0mnd5fcxOckZoONmUro2QTKEF75Uvqq5f%2FSWAbLm6ghwGCmAp6IHa8UsUrJrTL4tNxuJ7fm6V8ykBgxd5KNO6AfjBKYJyqQOFL4Drt6zrAYVViVXdhdN5U1OrsZ1lJDE%2BEkkWO%2FAGV49uhqfyfliKilpTzhnoXL3JuhNKbI5xntIos7xVzCOiE0PnIaiqOZu9WvfI%2FRIcP%2BZ7vDNLNIkuYmtPkqI7HMAwjZWVEtrDb0K6zOGQjjAwpCyWSCtv0bMODiWxNluLIA%3D%3D",
    mrf_status_date: null,
    employee: 133518,
    assigned_recruter: null,
    position_type_fk: 204,
    department_fk: 257,
    branch: 185,
    location: 67,
    academic_year_fk: 1,
    additional_recruiter: [],
  },
  {
    id: 1206,
    assigned_recruiter_name: null,
    branch_name: "OIS Jalahalli",
    verified_by: null,
    location_name: "Bangalore",
    position_apply_id: null,
    designation_fk_name: "Secondary Teacher - English",
    academic_year: "2024-2025",
    employee_name: "Divya M",
    mrf_type: "buffer",
    position: "Secondary English",
    position_type: null,
    department: null,
    zone: null,
    gender_preference: "any",
    experience: "3-5",
    priority: 1,
    minimum_qualification: "graduate_non_technical",
    no_of_vacancies: 1,
    max_budget: null,
    salary: "3-5",
    description:
      "<p><span style=\"color: #474747; font-family: 'Google Sans', arial, sans-serif; font-size: 16px; background-color: #ffffff;\">As an English teacher you'd&nbsp;</span><span style=\"background-color: #d3e3fd; color: #040c28; font-family: 'Google Sans', arial, sans-serif; font-size: 16px;\">help your pupils develop their language and literacy skills in listening and talking, reading and writing</span><span style=\"color: #474747; font-family: 'Google Sans', arial, sans-serif; font-size: 16px; background-color: #ffffff;\">. You'd help them read and enjoy literature and create their own texts.</span></p>",
    description_file: null,
    skill: "good communication and high expiernce",
    job_type: "Part Time",
    is_active: false,
    status: "hold",
    remark: "",
    mrf_replacement_emp_name: null,
    mrf_replacement_emp_id: null,
    replacement_json: null,
    updated_at: "2024-04-15T16:54:35.916073",
    created_at: "2024-04-02T16:40:20.351268",
    file: null,
    mrf_status_date: null,
    employee: 132895,
    assigned_recruter: null,
    position_type_fk: 262,
    department_fk: 1169,
    branch: 18,
    location: 2,
    academic_year_fk: 1,
    additional_recruiter: [],
  },
  {
    id: 1117,
    assigned_recruiter_name: null,
    branch_name: "OIS Jalahalli",
    verified_by: null,
    location_name: "Bangalore",
    position_apply_id: null,
    designation_fk_name: "Teacher - Music",
    academic_year: "2024-2025",
    employee_name: "Divya M",
    mrf_type: "buffer",
    position: "Teacher Music",
    position_type: null,
    department: null,
    zone: null,
    gender_preference: "any",
    experience: "3-5",
    priority: 1,
    minimum_qualification: "graduate_non_technical",
    no_of_vacancies: 1,
    max_budget: null,
    salary: "3-5",
    description:
      "<p>A music teacher is a professional who teaches music as a subject in the school curriculum. Music teachers instruct students in practical methods and theory of general music, singing, as well as playing musical instruments.</p>",
    description_file: null,
    skill: "good communication and music knowlege",
    job_type: "Full Time",
    is_active: false,
    status: "hold",
    remark: "",
    mrf_replacement_emp_name: null,
    mrf_replacement_emp_id: null,
    replacement_json: null,
    updated_at: "2024-05-10T15:11:39.584950",
    created_at: "2024-03-27T16:28:20.329474",
    file: null,
    mrf_status_date: null,
    employee: 132895,
    assigned_recruter: null,
    position_type_fk: 262,
    department_fk: 1226,
    branch: 18,
    location: 2,
    academic_year_fk: 1,
    additional_recruiter: [],
  },
];

export default data;
